[project]
org-name = "hemika"
version = "1.0.0"

license= ["Apache 2.0"]
authors= ["Hemika Kodikara"]
keywords= ["smtp", "email"]
repository= "https://github.com/hemikak/smtp"

[platform]
target = "java8"

  [[platform.libraries]]
  artifactId = "smtp-authenticator"
  version = "1.0.0"
  path = "libs/smtp-authenticator-1.0.0.jar"
  groupId = "org.hemikak.smtp"
  modules = ["smtp"]
